# Generated by Django 5.2.3 on 2025-06-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('length', models.DurationField()),
                ('number_of_songs', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
