# Generated by Django 5.2.3 on 2025-06-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_review_unique_user_album_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='no-heaven-here', unique=True),
            preserve_default=False,
        ),
    ]
