# Generated by Django 5.2.3 on 2025-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0008_genre_album_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
