# Generated by Django 5.2.3 on 2025-06-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_alter_album_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
    ]
